// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_dashw
NumericVector cpp_dashw(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dashw(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dashw(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pashw
NumericVector cpp_pashw(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pashw(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pashw(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qashw
NumericVector cpp_qashw(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qashw(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qashw(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rashw
NumericVector cpp_rashw(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_rashw(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rashw(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dbessel
NumericVector cpp_dbessel(NumericVector x, NumericVector mu, NumericVector phi, bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dbessel(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dbessel(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pbessel
NumericVector cpp_pbessel(NumericVector q, NumericVector mu, NumericVector phi, bool lower_tail, bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pbessel(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pbessel(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qbessel
NumericVector cpp_qbessel(NumericVector p, NumericVector mu, NumericVector phi, bool lower_tail, bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qbessel(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qbessel(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rbessel
NumericVector cpp_rbessel(int n, NumericVector mu, NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rbessel(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rbessel(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dbeta_mean
NumericVector cpp_dbeta_mean(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dbeta_mean(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dbeta_mean(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pbeta_mean
NumericVector cpp_pbeta_mean(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pbeta_mean(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pbeta_mean(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qbeta_mean
NumericVector cpp_qbeta_mean(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qbeta_mean(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qbeta_mean(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rbeta_mean
NumericVector cpp_rbeta_mean(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rbeta_mean(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rbeta_mean(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dbeta_mode
NumericVector cpp_dbeta_mode(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dbeta_mode(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dbeta_mode(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pbeta_mode
NumericVector cpp_pbeta_mode(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pbeta_mode(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pbeta_mode(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qbeta_mode
NumericVector cpp_qbeta_mode(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qbeta_mode(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qbeta_mode(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rbeta_mode
NumericVector cpp_rbeta_mode(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rbeta_mode(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rbeta_mode(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_djohnsonsb
NumericVector cpp_djohnsonsb(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_djohnsonsb(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_djohnsonsb(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pjohnsonsb
NumericVector cpp_pjohnsonsb(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pjohnsonsb(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pjohnsonsb(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qjohnsonsb
NumericVector cpp_qjohnsonsb(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qjohnsonsb(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qjohnsonsb(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rjohnsonsb
NumericVector cpp_rjohnsonsb(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_rjohnsonsb(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rjohnsonsb(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dkum_mode
NumericVector cpp_dkum_mode(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dkum_mode(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dkum_mode(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pkum_mode
NumericVector cpp_pkum_mode(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pkum_mode(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pkum_mode(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qkum_mode
NumericVector cpp_qkum_mode(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qkum_mode(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qkum_mode(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rkum_mode
NumericVector cpp_rkum_mode(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rkum_mode(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rkum_mode(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dkum_quantile
NumericVector cpp_dkum_quantile(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dkum_quantile(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dkum_quantile(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pkum_quantile
NumericVector cpp_pkum_quantile(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pkum_quantile(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pkum_quantile(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qkum_quantile
NumericVector cpp_qkum_quantile(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qkum_quantile(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qkum_quantile(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rkum_quantile
NumericVector cpp_rkum_quantile(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_rkum_quantile(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rkum_quantile(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dsimplex
NumericVector cpp_dsimplex(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dsimplex(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dsimplex(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_psimplex
NumericVector cpp_psimplex(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_psimplex(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_psimplex(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qsimplex
NumericVector cpp_qsimplex(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qsimplex(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qsimplex(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rsimplex
NumericVector cpp_rsimplex(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rsimplex(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rsimplex(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dubs
NumericVector cpp_dubs(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dubs(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dubs(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pubs
NumericVector cpp_pubs(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pubs(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pubs(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qubs
NumericVector cpp_qubs(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qubs(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qubs(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rubs
NumericVector cpp_rubs(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_rubs(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rubs(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dugamma_mean
NumericVector cpp_dugamma_mean(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dugamma_mean(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dugamma_mean(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pugamma_mean
NumericVector cpp_pugamma_mean(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pugamma_mean(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pugamma_mean(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qugamma_mean
NumericVector cpp_qugamma_mean(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qugamma_mean(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qugamma_mean(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rugamma_mean
NumericVector cpp_rugamma_mean(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rugamma_mean(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rugamma_mean(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dugamma_mode
NumericVector cpp_dugamma_mode(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dugamma_mode(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dugamma_mode(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pugamma_mode
NumericVector cpp_pugamma_mode(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pugamma_mode(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pugamma_mode(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qugamma_mode
NumericVector cpp_qugamma_mode(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qugamma_mode(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qugamma_mode(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rugamma_mode
NumericVector cpp_rugamma_mode(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rugamma_mode(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rugamma_mode(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dugompertz_mode
NumericVector cpp_dugompertz_mode(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dugompertz_mode(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dugompertz_mode(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pugompertz_mode
NumericVector cpp_pugompertz_mode(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pugompertz_mode(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pugompertz_mode(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qugompertz_mode
NumericVector cpp_qugompertz_mode(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qugompertz_mode(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qugompertz_mode(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rugompertz_mode
NumericVector cpp_rugompertz_mode(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rugompertz_mode(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rugompertz_mode(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dugompertz_quantile
NumericVector cpp_dugompertz_quantile(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dugompertz_quantile(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dugompertz_quantile(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pugompertz_quantile
NumericVector cpp_pugompertz_quantile(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pugompertz_quantile(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pugompertz_quantile(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qugompertz_quantile
NumericVector cpp_qugompertz_quantile(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qugompertz_quantile(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qugompertz_quantile(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rugompertz_quantile
NumericVector cpp_rugompertz_quantile(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_rugompertz_quantile(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rugompertz_quantile(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_duweibull
NumericVector cpp_duweibull(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_duweibull(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_duweibull(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_puweibull
NumericVector cpp_puweibull(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_puweibull(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_puweibull(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quweibull
NumericVector cpp_quweibull(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_quweibull(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quweibull(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ruweibull
NumericVector cpp_ruweibull(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_ruweibull(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ruweibull(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dvasicek_mean
NumericVector cpp_dvasicek_mean(const NumericVector x, const NumericVector mu, const NumericVector phi, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dvasicek_mean(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dvasicek_mean(x, mu, phi, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pvasicek_mean
NumericVector cpp_pvasicek_mean(const NumericVector q, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pvasicek_mean(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pvasicek_mean(q, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qvasicek_mean
NumericVector cpp_qvasicek_mean(const NumericVector p, const NumericVector mu, const NumericVector phi, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qvasicek_mean(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qvasicek_mean(p, mu, phi, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rvasicek_mean
NumericVector cpp_rvasicek_mean(const int n, const NumericVector mu, const NumericVector phi);
RcppExport SEXP _unitregTMB_cpp_rvasicek_mean(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rvasicek_mean(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dvasicek_quantile
NumericVector cpp_dvasicek_quantile(const NumericVector x, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_dvasicek_quantile(SEXP xSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dvasicek_quantile(x, mu, phi, tau, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pvasicek_quantile
NumericVector cpp_pvasicek_quantile(const NumericVector q, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_pvasicek_quantile(SEXP qSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pvasicek_quantile(q, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qvasicek_quantile
NumericVector cpp_qvasicek_quantile(const NumericVector p, const NumericVector mu, const NumericVector phi, const NumericVector tau, const bool lower_tail, const bool log_prob);
RcppExport SEXP _unitregTMB_cpp_qvasicek_quantile(SEXP pSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_prob(log_probSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qvasicek_quantile(p, mu, phi, tau, lower_tail, log_prob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rvasicek_quantile
NumericVector cpp_rvasicek_quantile(const int n, const NumericVector mu, const NumericVector phi, const NumericVector tau);
RcppExport SEXP _unitregTMB_cpp_rvasicek_quantile(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rvasicek_quantile(n, mu, phi, tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_unitregTMB_cpp_dashw", (DL_FUNC) &_unitregTMB_cpp_dashw, 5},
    {"_unitregTMB_cpp_pashw", (DL_FUNC) &_unitregTMB_cpp_pashw, 6},
    {"_unitregTMB_cpp_qashw", (DL_FUNC) &_unitregTMB_cpp_qashw, 6},
    {"_unitregTMB_cpp_rashw", (DL_FUNC) &_unitregTMB_cpp_rashw, 4},
    {"_unitregTMB_cpp_dbessel", (DL_FUNC) &_unitregTMB_cpp_dbessel, 4},
    {"_unitregTMB_cpp_pbessel", (DL_FUNC) &_unitregTMB_cpp_pbessel, 5},
    {"_unitregTMB_cpp_qbessel", (DL_FUNC) &_unitregTMB_cpp_qbessel, 5},
    {"_unitregTMB_cpp_rbessel", (DL_FUNC) &_unitregTMB_cpp_rbessel, 3},
    {"_unitregTMB_cpp_dbeta_mean", (DL_FUNC) &_unitregTMB_cpp_dbeta_mean, 4},
    {"_unitregTMB_cpp_pbeta_mean", (DL_FUNC) &_unitregTMB_cpp_pbeta_mean, 5},
    {"_unitregTMB_cpp_qbeta_mean", (DL_FUNC) &_unitregTMB_cpp_qbeta_mean, 5},
    {"_unitregTMB_cpp_rbeta_mean", (DL_FUNC) &_unitregTMB_cpp_rbeta_mean, 3},
    {"_unitregTMB_cpp_dbeta_mode", (DL_FUNC) &_unitregTMB_cpp_dbeta_mode, 4},
    {"_unitregTMB_cpp_pbeta_mode", (DL_FUNC) &_unitregTMB_cpp_pbeta_mode, 5},
    {"_unitregTMB_cpp_qbeta_mode", (DL_FUNC) &_unitregTMB_cpp_qbeta_mode, 5},
    {"_unitregTMB_cpp_rbeta_mode", (DL_FUNC) &_unitregTMB_cpp_rbeta_mode, 3},
    {"_unitregTMB_cpp_djohnsonsb", (DL_FUNC) &_unitregTMB_cpp_djohnsonsb, 5},
    {"_unitregTMB_cpp_pjohnsonsb", (DL_FUNC) &_unitregTMB_cpp_pjohnsonsb, 6},
    {"_unitregTMB_cpp_qjohnsonsb", (DL_FUNC) &_unitregTMB_cpp_qjohnsonsb, 6},
    {"_unitregTMB_cpp_rjohnsonsb", (DL_FUNC) &_unitregTMB_cpp_rjohnsonsb, 4},
    {"_unitregTMB_cpp_dkum_mode", (DL_FUNC) &_unitregTMB_cpp_dkum_mode, 4},
    {"_unitregTMB_cpp_pkum_mode", (DL_FUNC) &_unitregTMB_cpp_pkum_mode, 5},
    {"_unitregTMB_cpp_qkum_mode", (DL_FUNC) &_unitregTMB_cpp_qkum_mode, 5},
    {"_unitregTMB_cpp_rkum_mode", (DL_FUNC) &_unitregTMB_cpp_rkum_mode, 3},
    {"_unitregTMB_cpp_dkum_quantile", (DL_FUNC) &_unitregTMB_cpp_dkum_quantile, 5},
    {"_unitregTMB_cpp_pkum_quantile", (DL_FUNC) &_unitregTMB_cpp_pkum_quantile, 6},
    {"_unitregTMB_cpp_qkum_quantile", (DL_FUNC) &_unitregTMB_cpp_qkum_quantile, 6},
    {"_unitregTMB_cpp_rkum_quantile", (DL_FUNC) &_unitregTMB_cpp_rkum_quantile, 4},
    {"_unitregTMB_cpp_dsimplex", (DL_FUNC) &_unitregTMB_cpp_dsimplex, 4},
    {"_unitregTMB_cpp_psimplex", (DL_FUNC) &_unitregTMB_cpp_psimplex, 5},
    {"_unitregTMB_cpp_qsimplex", (DL_FUNC) &_unitregTMB_cpp_qsimplex, 5},
    {"_unitregTMB_cpp_rsimplex", (DL_FUNC) &_unitregTMB_cpp_rsimplex, 3},
    {"_unitregTMB_cpp_dubs", (DL_FUNC) &_unitregTMB_cpp_dubs, 5},
    {"_unitregTMB_cpp_pubs", (DL_FUNC) &_unitregTMB_cpp_pubs, 6},
    {"_unitregTMB_cpp_qubs", (DL_FUNC) &_unitregTMB_cpp_qubs, 6},
    {"_unitregTMB_cpp_rubs", (DL_FUNC) &_unitregTMB_cpp_rubs, 4},
    {"_unitregTMB_cpp_dugamma_mean", (DL_FUNC) &_unitregTMB_cpp_dugamma_mean, 4},
    {"_unitregTMB_cpp_pugamma_mean", (DL_FUNC) &_unitregTMB_cpp_pugamma_mean, 5},
    {"_unitregTMB_cpp_qugamma_mean", (DL_FUNC) &_unitregTMB_cpp_qugamma_mean, 5},
    {"_unitregTMB_cpp_rugamma_mean", (DL_FUNC) &_unitregTMB_cpp_rugamma_mean, 3},
    {"_unitregTMB_cpp_dugamma_mode", (DL_FUNC) &_unitregTMB_cpp_dugamma_mode, 4},
    {"_unitregTMB_cpp_pugamma_mode", (DL_FUNC) &_unitregTMB_cpp_pugamma_mode, 5},
    {"_unitregTMB_cpp_qugamma_mode", (DL_FUNC) &_unitregTMB_cpp_qugamma_mode, 5},
    {"_unitregTMB_cpp_rugamma_mode", (DL_FUNC) &_unitregTMB_cpp_rugamma_mode, 3},
    {"_unitregTMB_cpp_dugompertz_mode", (DL_FUNC) &_unitregTMB_cpp_dugompertz_mode, 4},
    {"_unitregTMB_cpp_pugompertz_mode", (DL_FUNC) &_unitregTMB_cpp_pugompertz_mode, 5},
    {"_unitregTMB_cpp_qugompertz_mode", (DL_FUNC) &_unitregTMB_cpp_qugompertz_mode, 5},
    {"_unitregTMB_cpp_rugompertz_mode", (DL_FUNC) &_unitregTMB_cpp_rugompertz_mode, 3},
    {"_unitregTMB_cpp_dugompertz_quantile", (DL_FUNC) &_unitregTMB_cpp_dugompertz_quantile, 5},
    {"_unitregTMB_cpp_pugompertz_quantile", (DL_FUNC) &_unitregTMB_cpp_pugompertz_quantile, 6},
    {"_unitregTMB_cpp_qugompertz_quantile", (DL_FUNC) &_unitregTMB_cpp_qugompertz_quantile, 6},
    {"_unitregTMB_cpp_rugompertz_quantile", (DL_FUNC) &_unitregTMB_cpp_rugompertz_quantile, 4},
    {"_unitregTMB_cpp_duweibull", (DL_FUNC) &_unitregTMB_cpp_duweibull, 5},
    {"_unitregTMB_cpp_puweibull", (DL_FUNC) &_unitregTMB_cpp_puweibull, 6},
    {"_unitregTMB_cpp_quweibull", (DL_FUNC) &_unitregTMB_cpp_quweibull, 6},
    {"_unitregTMB_cpp_ruweibull", (DL_FUNC) &_unitregTMB_cpp_ruweibull, 4},
    {"_unitregTMB_cpp_dvasicek_mean", (DL_FUNC) &_unitregTMB_cpp_dvasicek_mean, 4},
    {"_unitregTMB_cpp_pvasicek_mean", (DL_FUNC) &_unitregTMB_cpp_pvasicek_mean, 5},
    {"_unitregTMB_cpp_qvasicek_mean", (DL_FUNC) &_unitregTMB_cpp_qvasicek_mean, 5},
    {"_unitregTMB_cpp_rvasicek_mean", (DL_FUNC) &_unitregTMB_cpp_rvasicek_mean, 3},
    {"_unitregTMB_cpp_dvasicek_quantile", (DL_FUNC) &_unitregTMB_cpp_dvasicek_quantile, 5},
    {"_unitregTMB_cpp_pvasicek_quantile", (DL_FUNC) &_unitregTMB_cpp_pvasicek_quantile, 6},
    {"_unitregTMB_cpp_qvasicek_quantile", (DL_FUNC) &_unitregTMB_cpp_qvasicek_quantile, 6},
    {"_unitregTMB_cpp_rvasicek_quantile", (DL_FUNC) &_unitregTMB_cpp_rvasicek_quantile, 4},
    {NULL, NULL, 0}
};

void my_tmb_init(DllInfo *dll);
RcppExport void R_init_unitregTMB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    my_tmb_init(dll);
}
