###############################################################################
## unitregTMB: An R package for modeling correlated continuous bounded data ---
## Author: Ricardo Rasmussen Petterle UFPR ------------------------------------
## Date: March 14, 2026 -------------------------------------------------------
###############################################################################

#' Likelihood Ratio Tests for unitregTMB Models
#' 
#' @description 
#' Computes an analysis of deviance table for two or more fitted \code{unitregTMB} 
#' models. This function performs a Likelihood Ratio Test (LRT) to compare nested models, 
#' providing statistics such as degrees of freedom, AIC, BIC, log-likelihood, 
#' and the corresponding p-value.
#' 
#' @param object A fitted model object of class \code{unitregTMB}.
#' @param ... Additional fitted model objects of class \code{unitregTMB} to be compared. 
#'   At least one additional model must be provided.
#' @param test A character string specifying the test statistic to use. Currently, 
#'   the only supported option is \code{"Chisq"}, which computes the Likelihood 
#'   Ratio Test based on the Chi-square distribution.
#' 
#' @return An object of class \code{anova.unitregTMB} inheriting from \code{data.frame}. 
#'   The returned data frame contains the following columns:
#'   \item{Df}{The number of estimated parameters in the model.}
#'   \item{AIC}{Akaike Information Criterion.}
#'   \item{BIC}{Bayesian Information Criterion.}
#'   \item{logLik}{The log-likelihood of the model.}
#'   \item{deviance}{The deviance of the model (-2 * log-likelihood).}
#'   \item{Chisq}{The test statistic for the likelihood ratio test.}
#'   \item{Chi Df}{The difference in degrees of freedom between the models.}
#'   \item{Pr(>Chisq)}{The p-value associated with the likelihood ratio test.}
#' 
#' @author Ricardo Rasmussen Petterle
#' 
#' @examples
#' \dontrun{
#' # Assuming fit1 and fit2 are fitted unitregTMB models
#' # fit1 <- unitregTMB(y ~ x1, data = da, family = "beta")
#' # fit2 <- unitregTMB(y ~ x1 + x2, data = da, family = "beta")
#' # anova(fit1, fit2)
#' }
#' 
#' @export
anova.unitregTMB <- function(object, ..., test = "Chisq") {
  models <- list(object, ...)
  nmodels <- length(models)
  
  if (nmodels < 2) {
    stop("It is necessary to provide at least two models for comparison.")
  }
  info <- lapply(models, function(mod) {
    ll <- logLik(mod)
    data.frame(
      Df = as.integer(attr(ll, "df")),
      AIC = AIC(mod),
      BIC = BIC(mod),
      logLik = as.numeric(ll),
      deviance = -2 * as.numeric(ll),
      formula = deparse(formula(mod)) 
    )
  })
  tab <- do.call(rbind, info)
  model_names <- as.character(match.call(expand.dots = TRUE))[-1]
  model_names <- model_names[seq_len(nmodels)]
  rownames(tab) <- model_names
  tab <- tab[order(tab$Df), ]
  
  tab$Chisq <- c(NA, 2 * diff(tab$logLik))
  tab$`Chi Df` <- c(NA, diff(tab$Df))
  if (test == "Chisq") {
    tab$`Pr(>Chisq)` <- c(NA, pchisq(tab$Chisq[-1], df = tab$`Chi Df`[-1], lower.tail = FALSE))
  } else {
    tab$`Pr(>Chisq)` <- NA
  }
  formulas <- tab$formula
  tab$formula <- NULL
  attr(tab, "heading") <- "Likelihood ratio tests of unitregTMB models:"
  attr(tab, "models") <- formulas
  attr(tab, "model_names") <- rownames(tab)
  class(tab) <- c("anova.unitregTMB", "data.frame")
  return(tab)
}

#' Print Method for anova.unitregTMB Objects
#' 
#' @description 
#' Custom print method for displaying the analysis of deviance table 
#' generated by \code{anova.unitregTMB}.
#' 
#' @param x An object of class \code{anova.unitregTMB}.
#' @param ... Further arguments passed to or from other methods.
#' 
#' @return Invisibly returns the original \code{anova.unitregTMB} object.
#' 
#' @export
print.anova.unitregTMB <- function(x, ...) {
  if (!is.null(attr(x, "heading"))) cat(attr(x, "heading"), "\n")
  model_names <- attr(x, "model_names")
  formulas <- attr(x, "models")
  if (!is.null(model_names) && !is.null(formulas)) {
    cat("Models:\n")
    for (i in seq_along(model_names)) {
      cat(model_names[i], ": ", formulas[i], "\n", sep = "")
    }
    cat("\n")
  }
  
  df_to_print <- x
  attr(df_to_print, "heading") <- NULL
  attr(df_to_print, "models") <- NULL
  attr(df_to_print, "model_names") <- NULL
  class(df_to_print) <- "data.frame"
  
  pvals <- x$`Pr(>Chisq)`
  
  df_to_print$Df <- as.integer(df_to_print$Df)
  df_to_print$`Chi Df` <- as.integer(df_to_print$`Chi Df`)
  df_to_print$AIC <- format(round(df_to_print$AIC, 2), nsmall = 2)
  df_to_print$BIC <- format(round(df_to_print$BIC, 2), nsmall = 2)
  df_to_print$logLik <- format(round(df_to_print$logLik, 2), nsmall = 2)
  df_to_print$deviance <- format(round(df_to_print$deviance, 2), nsmall = 2)
  
  df_to_print$Chisq <- ifelse(is.na(x$Chisq), "", format(round(x$Chisq, 4), nsmall = 4))
  
  formatted_pvals <- format.pval(pvals, digits = 4, eps = 1e-4)
  df_to_print$`Pr(>Chisq)` <- ifelse(is.na(pvals), "", format(formatted_pvals, justify = "right"))
  
  df_to_print$`Chi Df`[is.na(df_to_print$`Chi Df`)] <- ""
  
  has_pvals <- any(!is.na(pvals))
  show_stars <- getOption("show.signif.stars", TRUE)
  
  if (has_pvals && show_stars) {
    Signif <- symnum(pvals, corr = FALSE, na = FALSE, 
                     cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), 
                     symbols = c("***", "**", "*", ".", " "))
    
    df_to_print$Signif <- as.character(Signif)
    df_to_print$Signif[is.na(pvals)] <- ""
    
    names(df_to_print)[ncol(df_to_print)] <- "" 
  }
  
  print(df_to_print, right = TRUE, quote = FALSE)
  
  if (has_pvals && show_stars) {
    cat("---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n")
  }
  
  invisible(x)
}
