#' @name JohnsonSB
#' @aliases JohnsonSB djohnsonsb pjohnsonsb qjohnsonsb rjohnsonsb
#' 
#' @title Johnson SB Distribution
#' 
#' @description 
#' Density, distribution function, quantile function, and random number generation for the 
#' Johnson SB distribution parameterized by a quantile \code{mu} at level \code{tau}.
#' 
#' @author Ricardo Rasmussen Petterle
#' 
#' @references 
#' Johnson, N. L. (1949). Systems of frequency curves generated by methods of translation. 
#' \emph{Biometrika}, 36(1/2), 149-176.
#'
#' Lemonte, A. J. and Bazán, J. L., (2015). New class of Johnson SB distributions and its associated regression model 
#' for rates and proportions. Biometrical Journal, 58(4), 727--746.
#' 
#' @param x,q vector of quantiles.
#' @param p vector of probabilities.
#' @param n number of observations.
#' @param mu quantile parameter (0 < mu < 1).
#' @param phi shape/precision parameter (phi > 0).
#' @param tau the quantile level (0 < tau < 1). Defaults to 0.5 (median).
#' @param log,log.p logical; if TRUE, probabilities p are given as log(p).
#' @param lower.tail logical; if TRUE (default), probabilities are \eqn{P[X \le x]}.
#' 
#' @examples
#' # 1. Set parameters
#' mu_val <- 0.7
#' phi_val <- 1.0
#' tau_val <- 0.5
#' 
#' # 2. Generate random values
#' set.seed(123)
#' x <- rjohnsonsb(1000, mu_val, phi_val, tau_val)
#' 
#' # 3. Visualization
#' hist(x, prob = TRUE, main = "Johnson SB", col = "lightgray")
#' curve(djohnsonsb(x, mu_val, phi_val, tau_val), add = TRUE, col = "red", lwd = 2)
#' 
NULL

#' @rdname JohnsonSB
#' @export
djohnsonsb <- function(x, mu, phi, tau = 0.5, log = FALSE) {
  stopifnot(mu > 0, mu < 1, phi > 0, tau > 0, tau < 1)
  cpp_djohnsonsb(x, mu, phi, tau, log[1L])
}

#' @rdname JohnsonSB
#' @export
pjohnsonsb <- function(q, mu, phi, tau = 0.5, lower.tail = TRUE, log.p = FALSE) {
  stopifnot(mu > 0, mu < 1, phi > 0, tau > 0, tau < 1)
  cpp_pjohnsonsb(q, mu, phi, tau, lower.tail[1L], log.p[1L])
}

#' @rdname JohnsonSB
#' @export
qjohnsonsb <- function(p, mu, phi, tau = 0.5, lower.tail = TRUE, log.p = FALSE) {
  stopifnot(mu > 0, mu < 1, phi > 0, tau > 0, tau < 1)
  cpp_qjohnsonsb(p, mu, phi, tau, lower.tail[1L], log.p[1L])
}

#' @rdname JohnsonSB
#' @export
rjohnsonsb <- function(n, mu, phi, tau = 0.5) {
  stopifnot(n > 0, mu > 0, mu < 1, phi > 0, tau > 0, tau < 1)
  cpp_rjohnsonsb(n, mu, phi, tau)
}
