#' @title Print Regression Coefficients in LaTeX for unitregTMB
#' 
#' @description 
#' Generates a LaTeX formatted table of regression coefficients, standard errors, 
#' z-values, and p-values for a fitted \code{unitregTMB} model.
#' 
#' @param model A fitted \code{unitregTMB} model.
#' @param digits Integer. Number of decimal places for estimates, standard errors, and z-values. Default is 3.
#' @param p_digits Integer. Number of decimal places for p-values. Default is 3.
#' @param custom_labels Named character vector; pairs of old variable names and desired new labels 
#'        to format the LaTeX output nicely. Default is \code{NULL}.
#' 
#' @return A character string (invisibly) containing the LaTeX code for the table. 
#'   The code is also printed directly to the console.
#' 
#' @examples
#' \donttest{
#' # Assuming 'fit' is a fitted unitregTMB model:
#' # Print the LaTeX table directly to the console
#' # print_tex_summary(fit)
#' 
#' # Save the table to an object and export to a .tex file
#' # tex_table <- print_tex_summary(fit, custom_labels = c("educHS+" = "High School"))
#' # writeLines(tex_table, "my_model_table.tex")
#' }
#' 
#' @export
print_tex_summary <- function(model, digits = 3, p_digits = 3, custom_labels = NULL) {
  sd_rep <- if (!is.null(model$sd_report)) model$sd_report else model$sdreport
  if (is.null(sd_rep)) stop("Model must be fitted with standard errors (sdreport/sd_report).")
  
  summ <- summary(sd_rep, "fixed")
  
  lines_out <- c(
    "\n% --- LaTeX Table generated by unitregTMB ---",
    "\\begin{table}[ht]",
    "\\centering",
    "\\begin{tabular}{lcccc}",
    "\\hline",
    "\\textbf{Parameter} & \\textbf{Estimate} & \\textbf{Std. Error} & \\textbf{z value} & \\textbf{Pr($>|z|$)} \\\\ \\hline"
  )
  
  fam_name <- if (is.list(model$family) && !is.null(model$family$name)) {
    model$family$name
  } else if (!is.null(model$family)) {
    as.character(model$family)[1]
  } else {
    "Location"
  }
  if (trimws(fam_name) == "") fam_name <- "Location"
  
  components <- c("beta_mu", "beta_phi", "beta_p0", "beta_p1")
  comp_labels <- c(paste(fam_name, "Location model"), 
                   "Dispersion/Precision model", 
                   "Zero-Inflation model", 
                   "One-Inflation model")
  
  first_block <- TRUE 
  
  for (j in 1:4) {
    comp_prefix <- components[j]
    idx <- grep(paste0("^", comp_prefix), rownames(summ))
    
    if (length(idx) > 0) {
      
      if (!first_block) {
        lines_out <- c(lines_out, "\\hline")
      }
      
      lines_out <- c(lines_out, sprintf("\\multicolumn{5}{c}{%s} \\\\ \\hline", comp_labels[j]))
      
      first_block <- FALSE
      
      est <- summ[idx, 1]
      se  <- summ[idx, 2]
      z   <- est / se
      p   <- 2 * pnorm(-abs(z))
      
      mat_name <- switch(comp_prefix, "beta_mu" = "X_mu", "beta_phi" = "X_phi", "beta_p0" = "X_p0", "beta_p1" = "X_p1")
      term_names <- rep(comp_prefix, length(est))
      
      if (!is.null(model$obj$env$data[[mat_name]])) {
        real_names <- colnames(model$obj$env$data[[mat_name]])
        if (!is.null(real_names) && length(real_names) == length(est)) {
          term_names <- real_names
        } else {
          term_names <- paste0(comp_prefix, "_", 1:length(est))
        }
      }
      
      if (!is.null(custom_labels)) {
        matches <- match(term_names, names(custom_labels))
        term_names[!is.na(matches)] <- custom_labels[matches[!is.na(matches)]]
      }
      
      term_names <- gsub("_", "\\\\_", term_names)
      
      for (i in 1:length(est)) {
        p_str <- sprintf(paste0("%.", p_digits, "f"), p[i])
        if (p[i] < 10^(-p_digits)) p_str <- paste0("$< 0.", paste(rep("0", p_digits-1), collapse=""), "1$")
        lines_out <- c(lines_out, sprintf("%s & %.*f & %.*f & %.*f & %s \\\\", term_names[i], digits, est[i], digits, se[i], digits, z[i], p_str))
      }
    }
  }
  
  lines_out <- c(lines_out, "\\hline\n\\end{tabular}\n\\end{table}\n")
  
  final_tex <- paste(lines_out, collapse = "\n")
  cat(final_tex)
  invisible(final_tex)
}
