#' Print Regression Coefficients in LaTeX for unitregTMB
#' @export
print_tex_summary <- function(model, digits = 3, p_digits = 3, custom_labels = NULL) {
  # Suporta tanto sd_report quanto sdreport (prevenção)
  sd_rep <- if (!is.null(model$sd_report)) model$sd_report else model$sdreport
  if (is.null(sd_rep)) stop("Model must be fitted with standard errors (sdreport/sd_report).")
  
  summ <- summary(sd_rep, "fixed")
  
  cat("\n% --- LaTeX Table generated by unitregTMB ---\n\\begin{table}[ht]\n\\centering\n")
  cat("\\begin{tabular}{lcccc}\n\\hline\n\\textbf{Parameter} & \\textbf{Estimate} & \\textbf{Std. Error} & \\textbf{z value} & \\textbf{Pr($>|z|$)} \\\\ \\hline\n")
  
  # --- 1. Resgate Ultrasseguro da Família ---
  fam_name <- if (is.list(model$family) && !is.null(model$family$name)) {
    model$family$name
  } else if (!is.null(model$family)) {
    as.character(model$family)[1]
  } else {
    "Location"
  }
  if (trimws(fam_name) == "") fam_name <- "Location"
  
  components <- c("beta_mu", "beta_phi", "beta_p0", "beta_p1")
  comp_labels <- c(paste(fam_name, "Location model"), 
                   "Dispersion/Precision model", 
                   "Zero-Inflation model", 
                   "One-Inflation model")
  
  first_block <- TRUE # Variável de controle para adicionar as linhas divisórias
  
  for (j in 1:4) {
    comp_prefix <- components[j]
    idx <- grep(paste0("^", comp_prefix), rownames(summ))
    
    if (length(idx) > 0) {
      
      # ii) Adiciona \hline ACIMA do novo bloco (exceto se for o primeiro bloco)
      if (!first_block) {
        cat("\\hline\n")
      }
      
      # i) Adiciona \hline ABAIXO do título do sub-modelo
      cat(sprintf("\\multicolumn{5}{c}{%s} \\\\ \\hline\n", comp_labels[j]))
      
      first_block <- FALSE
      
      est <- summ[idx, 1]
      se  <- summ[idx, 2]
      z   <- est / se
      p   <- 2 * pnorm(-abs(z))
      
      # --- 2. Resgate dos Nomes Reais (Driblando o TMB) ---
      mat_name <- switch(comp_prefix, "beta_mu" = "X_mu", "beta_phi" = "X_phi", "beta_p0" = "X_p0", "beta_p1" = "X_p1")
      term_names <- rep(comp_prefix, length(est))
      
      # Puxa os colnames diretamente da matriz de dados enviada ao TMB
      if (!is.null(model$obj$env$data[[mat_name]])) {
        real_names <- colnames(model$obj$env$data[[mat_name]])
        if (!is.null(real_names) && length(real_names) == length(est)) {
          term_names <- real_names
        } else {
          term_names <- paste0(comp_prefix, "_", 1:length(est))
        }
      }
      
      if (!is.null(custom_labels)) {
        matches <- match(term_names, names(custom_labels))
        term_names[!is.na(matches)] <- custom_labels[matches[!is.na(matches)]]
      }
      
      # Escapa o "_" para o LaTeX não achar que é formatação matemática
      term_names <- gsub("_", "\\\\_", term_names)
      
      for (i in 1:length(est)) {
        p_str <- sprintf(paste0("%.", p_digits, "f"), p[i])
        if (p[i] < 10^(-p_digits)) p_str <- paste0("$< 0.", paste(rep("0", p_digits-1), collapse=""), "1$")
        cat(sprintf("%s & %.*f & %.*f & %.*f & %s \\\\ \n", term_names[i], digits, est[i], digits, se[i], digits, z[i], p_str))
      }
    }
  }
  cat("\\hline\n\\end{tabular}\n\\end{table}\n")
}