# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dashw <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dashw', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_pashw <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pashw', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_qashw <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qashw', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_rashw <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_rashw', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

cpp_dbessel <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dbessel', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pbessel <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pbessel', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qbessel <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qbessel', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rbessel <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rbessel', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dbeta_mean <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dbeta_mean', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pbeta_mean <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pbeta_mean', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qbeta_mean <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qbeta_mean', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rbeta_mean <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rbeta_mean', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dbeta_mode <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dbeta_mode', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pbeta_mode <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pbeta_mode', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qbeta_mode <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qbeta_mode', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rbeta_mode <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rbeta_mode', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_djohnsonsb <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_djohnsonsb', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_pjohnsonsb <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pjohnsonsb', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_qjohnsonsb <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qjohnsonsb', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_rjohnsonsb <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_rjohnsonsb', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

cpp_dkum_mode <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dkum_mode', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pkum_mode <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pkum_mode', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qkum_mode <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qkum_mode', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rkum_mode <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rkum_mode', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dkum_quantile <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dkum_quantile', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_pkum_quantile <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pkum_quantile', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_qkum_quantile <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qkum_quantile', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_rkum_quantile <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_rkum_quantile', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

cpp_dsimplex <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dsimplex', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_psimplex <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_psimplex', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qsimplex <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qsimplex', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rsimplex <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rsimplex', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dubs <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dubs', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_pubs <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pubs', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_qubs <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qubs', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_rubs <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_rubs', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

cpp_dugamma_mean <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dugamma_mean', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pugamma_mean <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pugamma_mean', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qugamma_mean <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qugamma_mean', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rugamma_mean <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rugamma_mean', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dugamma_mode <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dugamma_mode', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pugamma_mode <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pugamma_mode', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qugamma_mode <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qugamma_mode', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rugamma_mode <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rugamma_mode', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dugompertz_mode <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dugompertz_mode', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pugompertz_mode <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pugompertz_mode', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qugompertz_mode <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qugompertz_mode', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rugompertz_mode <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rugompertz_mode', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dugompertz_quantile <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dugompertz_quantile', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_pugompertz_quantile <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pugompertz_quantile', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_qugompertz_quantile <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qugompertz_quantile', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_rugompertz_quantile <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_rugompertz_quantile', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

cpp_duweibull <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_duweibull', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_puweibull <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_puweibull', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_quweibull <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_quweibull', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_ruweibull <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_ruweibull', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

cpp_dvasicek_mean <- function(x, mu, phi, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dvasicek_mean', PACKAGE = 'unitregTMB', x, mu, phi, log_prob)
}

cpp_pvasicek_mean <- function(q, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pvasicek_mean', PACKAGE = 'unitregTMB', q, mu, phi, lower_tail, log_prob)
}

cpp_qvasicek_mean <- function(p, mu, phi, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qvasicek_mean', PACKAGE = 'unitregTMB', p, mu, phi, lower_tail, log_prob)
}

cpp_rvasicek_mean <- function(n, mu, phi) {
    .Call('_unitregTMB_cpp_rvasicek_mean', PACKAGE = 'unitregTMB', n, mu, phi)
}

cpp_dvasicek_quantile <- function(x, mu, phi, tau, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_dvasicek_quantile', PACKAGE = 'unitregTMB', x, mu, phi, tau, log_prob)
}

cpp_pvasicek_quantile <- function(q, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_pvasicek_quantile', PACKAGE = 'unitregTMB', q, mu, phi, tau, lower_tail, log_prob)
}

cpp_qvasicek_quantile <- function(p, mu, phi, tau, lower_tail = TRUE, log_prob = FALSE) {
    .Call('_unitregTMB_cpp_qvasicek_quantile', PACKAGE = 'unitregTMB', p, mu, phi, tau, lower_tail, log_prob)
}

cpp_rvasicek_quantile <- function(n, mu, phi, tau) {
    .Call('_unitregTMB_cpp_rvasicek_quantile', PACKAGE = 'unitregTMB', n, mu, phi, tau)
}

