#' @importFrom stats glm.fit quasibinomial coef fitted var model.matrix model.frame model.response qlogis pnorm as.formula
#' @importFrom reformulas findbars nobars subbars
#' @importFrom Matrix t Matrix KhatriRao fac2sparse
#' @importFrom TMB MakeADFun sdreport
#' @importFrom utils modifyList
#' @importFrom Rcpp sourceCpp
#' @useDynLib unitregTMB
NULL

## ----------------------------------------------------------------------------
## unitregTMB.control
## ----------------------------------------------------------------------------
#' @title Control Parameters for unitregTMB Model Fitting
#' 
#' @description 
#' Defines control parameters for the optimization process used in \code{unitregTMB}. 
#' It allows the user to specify evaluation and iteration limits, the choice of 
#' optimizer, and whether to compute standard errors via the TMB framework.
#' 
#' @param eval.max Maximum number of evaluations of the objective function allowed. Default is 2000.
#' @param iter.max Maximum number of iterations allowed. Default is 2000.
#' @param verbose Logical; if \code{TRUE}, optimization tracing information is printed. Default is \code{FALSE}.
#' @param sd.report Logical; if \code{TRUE}, standard errors are calculated using \code{TMB::sdreport}. Default is \code{TRUE}.
#' @param get.joint.precision Logical; if \code{TRUE}, the joint precision matrix is returned by \code{sdreport}. Default is \code{FALSE}.
#' @param optimizer A character string specifying the optimizer to use. Options are \code{"nlminb"} (default) or \code{"optim"}.
#' @param optim.method The method to be used if \code{optimizer = "optim"}. Default is \code{"BFGS"}.
#' @param optim.control A list of additional control parameters to be passed to the chosen optimizer.
#' @param ... Additional arguments.
#' 
#' @return A list containing the specified control parameters to be used in \code{unitregTMB.fit}.
#' 
#' @export
unitregTMB.control <- function(eval.max = 2000, 
                               iter.max = 2000,
                               verbose = FALSE, 
                               sd.report = TRUE, 
                               get.joint.precision = FALSE, 
                               optimizer = c("nlminb", "optim"),
                               optim.method = "BFGS",
                               optim.control = list(),
                               ...) {
  optimizer <- match.arg(optimizer)
  list(
    eval.max = eval.max, iter.max = iter.max, verbose = verbose,
    sd.report = sd.report, get.joint.precision = get.joint.precision, 
    optimizer = optimizer, optim.method = optim.method, optim.control = optim.control,
    ...
  )
}

## ----------------------------------------------------------------------------
## unitregTMB.fit
## ----------------------------------------------------------------------------
#' Fit a unitregTMB Model (Internal)
#' 
#' @description 
#' Internal function that acts as a wrapper for \code{TMB::MakeADFun} and the 
#' optimization algorithms (\code{nlminb} or \code{optim}) to fit the regression model.
#' 
#' @param data_tmb A list of data objects created internally by \code{unitregTMB} to be passed to TMB.
#' @param parameters A list of initial parameter values.
#' @param random_args A character vector indicating which parameters should be treated as random effects.
#' @param control A list of control parameters generated by \code{unitregTMB.control}.
#' @param silent Logical; if \code{TRUE}, disables TMB compilation and evaluation output.
#' 
#' @return A list containing the fitted TMB object, the optimization result, the standard error report, and convergence metrics.
#' 
#' @keywords internal
unitregTMB.fit <- function(data_tmb, parameters, random_args = NULL,
                           control = unitregTMB.control(), silent = FALSE) {
  
  obj <- TMB::MakeADFun(
    data = data_tmb, parameters = parameters, random = random_args,
    DLL = "unitregTMB", silent = silent
  )
  
  start_time <- Sys.time()
  optimizer_warnings <- character()
  
  capture_optimizer_warnings <- function(expr) {
    withCallingHandlers(
      expr,
      warning = function(w) {
        optimizer_warnings <<- c(optimizer_warnings, conditionMessage(w))
        if (!silent) message("Optimizer warning: ", conditionMessage(w))
        invokeRestart("muffleWarning")
      }
    )
  }
  
  if (control$optimizer == "nlminb") {
    nlminb_control <- modifyList(
      list(iter.max = control$iter.max, eval.max = control$eval.max, trace = if(control$verbose) 1 else 0),
      control$optim.control
    )
    opt <- capture_optimizer_warnings(
      nlminb(start = obj$par, objective = obj$fn, gradient = obj$gr, control = nlminb_control)
    )
  } else if (control$optimizer == "optim") {
    opt <- capture_optimizer_warnings(
      optim(par = obj$par, fn = obj$fn, gr = obj$gr, method = control$optim.method, control = control$optim.control)
    )
    opt$objective <- opt$value
  } else { stop("Unsupported optimizer.") }
  
  fitting_time <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
  
  raw_grad <- tryCatch(
    obj$gr(opt$par),
    error = function(e) {
      optimizer_warnings <<- c(optimizer_warnings, paste0("Final gradient evaluation failed: ", conditionMessage(e)))
      rep(NA_real_, length(opt$par))
    }
  )
  
  if (all(is.finite(raw_grad))) {
    max_grad <- max(abs(raw_grad))
  } else {
    max_grad <- Inf
  }
  
  sd_report <- NULL
  if (control$sd.report) {  
    if(control$verbose) cat("Calculating standard errors...\n")
    sd_report <- tryCatch({
      TMB::sdreport(obj, getJointPrecision = control$get.joint.precision)
    }, error = function(e) { 
      warning("sdreport failed: ", conditionMessage(e)); NULL 
    })
  }
  
  return(list(obj = obj, opt = opt, sd_report = sd_report, 
              convergence = opt$convergence, message = opt$message, 
              max_gradient = max_grad, full_gradient = raw_grad, 
              optimizer_warnings = unique(optimizer_warnings), 
              fitting_time = fitting_time))
}

## ----------------------------------------------------------------------------
## Auxiliar function for random effects 
## ----------------------------------------------------------------------------
#' Parse Random Effects Helper
#' 
#' @description 
#' Internal helper function that extracts and parses random effects structures 
#' from formulas, generating the necessary design matrices (\code{Z}) and group indicators 
#' required by the TMB objective function.
#' 
#' @param bars A list of random effects terms extracted from the model formula.
#' @param data The data frame containing the variables.
#' 
#' @return A list containing the sparse design matrix \code{Z}, column names, factors, and group names.
#' 
#' @keywords internal
parse_random_effects <- function(bars, data) {
  Z_list <- list()
  cnms <- list()
  flist <- list()
  group_names <- character(length(bars))
  
  for (i in seq_along(bars)) {
    bar <- bars[[i]]
    rhs_expr <- bar[[3]]
    rhs_str <- paste(deparse(rhs_expr), collapse = " ")
    group_names[i] <- rhs_str
    
    grp_vars <- all.vars(rhs_expr)
    if (length(grp_vars) > 1) {
      grp_factor <- interaction(data[grp_vars], drop = TRUE)
    } else {
      grp_factor <- as.factor(data[[grp_vars]])
    }
    
    flist[[i]] <- grp_factor
    names(flist)[i] <- rhs_str
    
    lhs_expr <- bar[[2]]
    lhs_str <- paste(deparse(lhs_expr), collapse = " ")
    lhs_formula <- stats::as.formula(paste("~", lhs_str))
    
    mf_re <- stats::model.frame(lhs_formula, data, na.action = stats::na.pass)
    X_re <- stats::model.matrix(lhs_formula, mf_re)
    
    cnms[[i]] <- colnames(X_re)
    
    A <- Matrix::fac2sparse(grp_factor) 
    B <- Matrix::t(X_re)                
    
    Zt_i <- Matrix::KhatriRao(A, B, make.dimnames = TRUE)
    Z_list[[i]] <- Matrix::t(Zt_i)
  }
  
  list(Z = do.call(cbind, Z_list), cnms = cnms, flist = flist, group_names = group_names)
}

## ----------------------------------------------------------------------------
## is_zero_formula Helper
## ----------------------------------------------------------------------------
#' Check for Empty Formulas
#' 
#' @description 
#' Internal function to verify if a given formula evaluates to an intercept-only 
#' model without any terms (e.g., \code{~ 0} or \code{~ -1}).
#' 
#' @param formula A formula object.
#' 
#' @return \code{TRUE} if the formula contains no predictors and no intercept, \code{FALSE} otherwise.
#' 
#' @keywords internal
is_zero_formula <- function(formula) {
  if (is.null(formula)) return(FALSE)
  trm <- stats::terms(formula)
  identical(attr(trm, "intercept"), 0L) && length(attr(trm, "term.labels")) == 0L
}

## ----------------------------------------------------------------------------
## unitregTMB (main function)
## ----------------------------------------------------------------------------
#' @title Fit Regression Models for Correlated Continuous Bounded Data
#' 
#' @description 
#' Fits regression models for data strictly or partially bounded in the unit interval 
#' [0, 1]. \code{unitregTMB} allows modeling the location (mean, mode, or quantile) 
#' and precision/dispersion parameters using fixed and random effects. It also 
#' natively supports exact zero- and one-inflation components for boundary observations.
#' 
#' @param formula A two-sided formula for the location parameter (e.g., \code{Y ~ x1 + x2}). 
#'   Random effects can be specified using the \code{lme4} syntax (e.g., \code{(1 | group)}).
#' @param data A data frame, list, or environment containing the variables in the model.
#' @param family A \code{unitregTMBFamily} object specifying the assumed distribution 
#'   (e.g., \code{beta_mean()}, \code{kumaraswamy_mode()}, \code{ashw(model_for = "quantile")}).
#' @param phi.formula A one-sided formula for the precision/shape parameter. Default is \code{~ 1}.
#' @param p0.formula A one-sided formula for the zero-inflation probability. If \code{NULL} and 
#'   exact zeros are present in the response, an intercept-only model is fitted by default.
#' @param p1.formula A one-sided formula for the one-inflation probability. If \code{NULL} and 
#'   exact ones are present in the response, an intercept-only model is fitted by default.
#' @param weights An optional vector of 'prior weights' to be used in the fitting process.
#' @param offset An optional vector to be added to the linear predictor for the location parameter.
#' @param subset An optional vector specifying a subset of observations to be used in the fitting process.
#' @param na.action A function which indicates what should happen when the data contain \code{NA}s. 
#'   The default is \code{na.omit}.
#' @param start An optional list of initial values for the model parameters.
#' @param control A list of control parameters returned by \code{unitregTMB.control}.
#' 
#' @details 
#' The function uses Template Model Builder (TMB) to efficiently evaluate the 
#' marginal log-likelihood via the Laplace approximation when random effects are present. 
#' The response variable must be bounded in the [0, 1] interval. If the response contains 
#' exactly 0s or 1s, the model automatically triggers the corresponding inflation sub-models 
#' (\code{p0.formula} and \code{p1.formula}).
#' 
#' @return An object of class \code{unitregTMB} containing the following components:
#' \item{obj}{The TMB object created by \code{MakeADFun}.}
#' \item{opt}{The optimization result returned by the chosen optimizer.}
#' \item{sd_report}{The standard error report generated by \code{TMB::sdreport}.}
#' \item{model_coef}{A list of the estimated coefficients for each model component (\code{mu}, \code{phi}, \code{p0}, \code{p1}).}
#' \item{model_std}{A list of standard errors corresponding to the estimated coefficients.}
#' \item{logLik}{The final maximized log-likelihood.}
#' \item{AIC}{Akaike Information Criterion.}
#' \item{BIC}{Bayesian Information Criterion.}
#' \item{fitted.values}{A list of fitted values based on the full model.}
#' \item{random_effects_variance}{A list of estimated variances and correlations for the random effects.}
#' 
#' @author Ricardo Rasmussen Petterle
#' 
#' @examples
#' \dontrun{
#' # Basic mean parameterization with Beta distribution
#' fit1 <- unitregTMB(yield ~ moisture + temp, data = crop_data, family = beta_fam(model_for = "mean"))
#' 
#' # Mixed-effects model with Kumaraswamy mode parameterization
#' fit2 <- unitregTMB(score ~ therapy + (1 | subject), 
#'                    data = clinical_data, 
#'                    family = kumaraswamy(model_for = "mode"))
#' 
#' # Model with zero-inflation and precision covariates
#' fit3 <- unitregTMB(fraction ~ x1, 
#'                    phi.formula = ~ x2,
#'                    p0.formula = ~ x1,
#'                    data = bound_data, 
#'                    family = unitweibull(model_for = "quantile", tau = 0.5))
#' }
#' 
#' @export
unitregTMB <- function(formula, data, family,
                       phi.formula = ~ 1, p0.formula = NULL, p1.formula = NULL,
                       weights = NULL, offset = NULL, 
                       subset, na.action, start = NULL, 
                       control = unitregTMB.control()) {
  
  cl <- match.call()
  
  if (!is.data.frame(data)) {
    data <- as.data.frame(data)
  }
  
  if (is.function(family)) { family <- family() }
  if (!inherits(family, "unitregTMBFamily")) 
    stop("Invalid family object.")
  
  valid_links <- c("logit", "probit", "cloglog", "cauchit")
  if (!family$link_r_name %in% valid_links) {
    stop("Unsupported mean link: ", family$link_r_name, ".")
  }
  
  valid_link_codes <- c(logit = 0L, probit = 1L, cloglog = 2L, cauchit = 3L)
  expected_link_code <- unname(valid_link_codes[family$link_r_name])
  
  if (length(family$link_code) != 1L || is.na(family$link_code) || 
      !is.numeric(family$link_code) || as.integer(family$link_code) != expected_link_code) {
    stop("Inconsistent link name and link code in the family object.")
  }

  re_list <- reformulas::findbars(formula)
  has_random <- length(re_list) > 0
  fixed_form <- reformulas::nobars(formula)
  
  full_form <- if(has_random) reformulas::subbars(formula) else formula
  all_forms <- list(full_form, phi.formula, p0.formula, p1.formula)
  all_forms <- all_forms[!sapply(all_forms, is.null)]
  
  all_vars <- unique(unlist(lapply(all_forms, all.vars)))
  resp_vars <- all.vars(full_form[[2]])
  pred_vars <- setdiff(all_vars, resp_vars)
  if (length(pred_vars) == 0) pred_vars <- "1"
  
  combined_formula <- stats::reformulate(termlabels = pred_vars, response = full_form[[2]], env = environment(formula))
  
  mf_call <- match.call(expand.dots = FALSE)
  m <- match(c("data", "subset", "na.action", "weights", "offset"), names(mf_call), 0L)
  mf_call <- mf_call[c(1L, m)]
  mf_call$formula <- combined_formula
  mf_call$drop.unused.levels <- TRUE
  
  if (is.null(mf_call$na.action)) {
    mf_call$na.action <- quote(stats::na.omit)
  }
  
  mf_call[[1L]] <- quote(stats::model.frame)
  mf <- eval(mf_call, parent.frame())
  
  clean_data <- data[rownames(mf), , drop = FALSE]
  
  Y <- stats::model.response(mf, "numeric")
  if (any(Y < 0 | Y > 1)) stop("Response must be bounded in the interval [0, 1].")

  y_class_vec <- ifelse(Y == 0, 0L, ifelse(Y == 1, 1L, 2L))
  
  if (is.null(p0.formula) && any(y_class_vec == 0L)) p0.formula <- ~ 1
  if (is.null(p1.formula) && any(y_class_vec == 1L)) p1.formula <- ~ 1
  
  has_p0 <- !is.null(p0.formula) && !is_zero_formula(p0.formula)
  has_p1 <- !is.null(p1.formula) && !is_zero_formula(p1.formula)
  
  if (any(y_class_vec == 0L) && !has_p0) stop("The response contains exact zeros, but the zero-inflation component is disabled.")
  if (any(y_class_vec == 1L) && !has_p1) stop("The response contains exact ones, but the one-inflation component is disabled.")
  
  n_obs_clean <- nrow(clean_data)
  
  weights_vec <- as.vector(stats::model.weights(mf))
  if (is.null(weights_vec)) {
    weights_vec <- rep(1.0, n_obs_clean)
  } else {
    if (anyNA(weights_vec) || any(!is.finite(weights_vec))) stop("Weights must be finite and non-missing.")
    if (any(weights_vec < 0)) stop("Weights cannot be negative.")
  }
  
  if (!any(weights_vec > 0)) stop("At least one observation must have a positive weight.")
  
  offset_vec <- as.vector(stats::model.offset(mf))
  if (is.null(offset_vec)) {
    offset_vec <- rep(0.0, n_obs_clean)
  } else {
    if (anyNA(offset_vec) || any(!is.finite(offset_vec))) stop("Offsets must be finite and non-missing.")
  }

  Z_mu <- Matrix::Matrix(0, nrow(clean_data), 0, sparse = TRUE)
  re_info <- list(has_random_effects = FALSE)
  re_n_comp <- integer(0); re_chol_start <- integer(0); u_start <- integer(0); n_lev_list <- integer(0)
  log_chol_init <- numeric(0)
  
  X_mu <- stats::model.matrix(fixed_form, clean_data)
  
  if (has_random) {
    re_parsed <- parse_random_effects(re_list, clean_data)
    Z_mu <- re_parsed$Z
    cnms <- re_parsed$cnms
    flist <- re_parsed$flist
    grp_names <- re_parsed$group_names
    
    curr_chol <- 0; curr_u <- 0
    for (i in seq_along(re_list)) {
      n_comp <- length(cnms[[i]])
      n_lev <- nlevels(flist[[i]])
      n_chol <- n_comp * (n_comp + 1) / 2
      
      re_n_comp <- c(re_n_comp, n_comp)
      re_chol_start <- c(re_chol_start, curr_chol)
      n_lev_list <- c(n_lev_list, n_lev)
      u_start <- c(u_start, curr_u)
      
      chol_vec <- rep(0.0, n_chol)
      diag_pos <- integer(n_comp)
      pos <- 1L
      for (j in seq_len(n_comp)) {
        diag_pos[j] <- pos
        pos <- pos + n_comp - j + 1L
      }
      chol_vec[diag_pos] <- log(0.5)
      log_chol_init <- c(log_chol_init, chol_vec)
      
      curr_chol <- curr_chol + n_chol
      curr_u <- curr_u + (n_comp * n_lev)
    }
    re_info <- list(has_random_effects = TRUE, n_re_terms = length(re_list),
                    re_term_n_components = re_n_comp, group_var_names = grp_names,
                    cnms = cnms, n_re_levels_list = n_lev_list, group_levels = lapply(flist, levels))
  }
  
  X_phi <- stats::model.matrix(phi.formula, clean_data)
  X_p0 <- if (has_p0) stats::model.matrix(p0.formula, clean_data) else matrix(0, nrow(clean_data), 0)
  X_p1 <- if (has_p1) stats::model.matrix(p1.formula, clean_data) else matrix(0, nrow(clean_data), 0)
  mt <- stats::terms(fixed_form, data = clean_data)
  
  check_dense_matrix <- function(x, name) {
    if (anyNA(x) || any(!is.finite(x))) {
      stop(name, " contains missing or non-finite values. Check transformations and covariates in the corresponding formula.")
    }
  }
  check_dense_matrix(X_mu, "X_mu")
  check_dense_matrix(X_phi, "X_phi")
  if (has_p0) check_dense_matrix(X_p0, "X_p0")
  if (has_p1) check_dense_matrix(X_p1, "X_p1")
  if (has_random && length(Z_mu@x) > 0L && any(!is.finite(Z_mu@x))) {
    stop("Z_mu contains non-finite values.")
  }

  if(control$verbose) cat("Calculating starting values...\n")
  
  interior <- y_class_vec == 2L & weights_vec > 0
  if (sum(interior) <= ncol(X_mu)) {
    stop("Too few positive-weight interior observations to initialize the continuous component.")
  }
  
  glm_fit <- tryCatch(
    stats::glm.fit(x = X_mu[interior, , drop = FALSE], 
                   y = Y[interior], 
                   weights = weights_vec[interior], 
                   offset = offset_vec[interior], 
                   family = stats::quasibinomial(family$link_r_name)),
    error = function(e) NULL
  )
  
  if (is.null(glm_fit)) {
    beta_mu_init <- rep(0, ncol(X_mu))
  } else {
    beta_mu_init <- as.numeric(stats::coef(glm_fit))
    beta_mu_init[!is.finite(beta_mu_init)] <- 0
  }
  
  linkobj_init <- stats::make.link(family$link_r_name)
  eta_mu_init <- drop(X_mu %*% beta_mu_init + offset_vec)
  mu_hat <- linkobj_init$linkinv(eta_mu_init)
  
  ## IDs: 0 (beta mean), 4 (bessel mean), 5 (beta mode)
  fam_precision_ids <- c(0L, 4L, 5L)
  if (family$family_code == 1L) {
  
  den <- pmax(mu_hat[interior]^3 * (1 - mu_hat[interior])^3, 1e-10)
  phi_est <- mean((Y[interior] - mu_hat[interior])^2 / den)
  phi_est <- pmin(pmax(phi_est, 1e-4), 100)

  } else if (family$family_code %in% fam_precision_ids) {
  var_est <- mean((Y[interior] - mu_hat[interior])^2)
  phi_est_raw <- mean(mu_hat[interior] * (1 - mu_hat[interior])) / (var_est + 1e-6) - 1
  phi_est <- pmin(pmax(phi_est_raw, 0.1), 100)
  } else {
  phi_est <- exp(1)
}

  beta_phi_init <- rep(0, ncol(X_phi))
  if (ncol(X_phi) > 0L) {
    if (family$family_code %in% c(2L, 10L)) {
      phi_start <- 0.5
      beta_phi_init[1] <- stats::qlogis(phi_start)
    } else {
    beta_phi_init[1] <- log(max(phi_est, 1e-4))
  }
}
  
  safe_prob <- function(p, eps = 1e-6) pmin(pmax(p, eps), 1 - eps)
  weighted_prop <- function(condition, weights) sum(weights * condition) / sum(weights)
  
  p0_start <- weighted_prop(Y == 0, weights_vec)
  p1_start <- weighted_prop(Y == 1, weights_vec)
  pc_start <- weighted_prop(Y > 0 & Y < 1, weights_vec)
  
  if (pc_start == 0) stop("No interior observations found. Continuous density parameters are not identifiable.")
  
  if (has_p0 && has_p1) {
    n0 <- sum(Y == 0); n1 <- sum(Y == 1); nc <- sum(Y > 0 & Y < 1)
    p0_sm <- (n0 + 0.5) / (length(Y) + 1.5)
    p1_sm <- (n1 + 0.5) / (length(Y) + 1.5)
    pc_sm <- (nc + 0.5) / (length(Y) + 1.5)
    beta_p0_init <- c(log(p0_sm / pc_sm), rep(0, ncol(X_p0) - 1))
    beta_p1_init <- c(log(p1_sm / pc_sm), rep(0, ncol(X_p1) - 1))
  } else if (has_p0) {
    beta_p0_init <- c(qlogis(safe_prob(p0_start)), rep(0, ncol(X_p0) - 1))
    beta_p1_init <- numeric(0)
  } else if (has_p1) {
    beta_p0_init <- numeric(0)
    beta_p1_init <- c(qlogis(safe_prob(p1_start)), rep(0, ncol(X_p1) - 1))
  } else {
    beta_p0_init <- numeric(0)
    beta_p1_init <- numeric(0)
  }
  
  pars <- list(beta_mu = as.numeric(beta_mu_init), beta_phi = as.numeric(beta_phi_init),
               beta_p0 = as.numeric(beta_p0_init), beta_p1 = as.numeric(beta_p1_init),
               u_mu = if(has_random) rep(0.0, ncol(Z_mu)) else numeric(0),
               log_chol_re_mu_combined = as.numeric(log_chol_init))
               
  if(!is.null(start)) {
    pars <- utils::modifyList(pars, start)
  } else if (!is.null(control$start)) {
    pars <- utils::modifyList(pars, control$start)
  }
  
  dt_tmb <- list(Y = as.numeric(Y), y_class = as.integer(y_class_vec), X_mu = X_mu, X_phi = X_phi, 
                 X_p0 = X_p0, X_p1 = X_p1, Z_mu = Z_mu, weights = weights_vec, offset_mu = offset_vec,
                 family = as.integer(family$family_code), link = as.integer(family$link_code),
                 tau = if(is.null(family$tau)) 0.0 else as.numeric(family$tau),
                 has_p0_inflation = as.integer(has_p0), has_p1_inflation = as.integer(has_p1),
                 has_random_effects_mu = as.integer(has_random),
                 re_term_n_components = as.integer(re_n_comp), re_term_chol_starts = as.integer(re_chol_start),
                 u_mu_term_starts = as.integer(u_start), n_re_levels_list_data = as.integer(n_lev_list))
  
  fit <- unitregTMB.fit(dt_tmb, pars, random_args = if(has_random) "u_mu" else NULL,
                        control = control, silent = !control$verbose)
  
  model_coef <- list(); model_std <- list()
  random_effects_variance <- NULL
  
  nms_mu <- colnames(X_mu); nms_phi <- colnames(X_phi)
  colnames_X_p0 <- if (has_p0) colnames(X_p0) else character(0)
  colnames_X_p1 <- if (has_p1) colnames(X_p1) else character(0)
  
  raw <- fit$opt$par
  model_coef$mu <- raw[names(raw)=="beta_mu"]; names(model_coef$mu) <- nms_mu
  model_coef$phi <- raw[names(raw)=="beta_phi"]; names(model_coef$phi) <- nms_phi
  if(has_p0) { model_coef$p0 <- raw[names(raw)=="beta_p0"]; names(model_coef$p0) <- colnames_X_p0 }
  if(has_p1) { model_coef$p1 <- raw[names(raw)=="beta_p1"]; names(model_coef$p1) <- colnames_X_p1 }
  
  model_std$std.mu  <- rep(NA_real_, length(model_coef$mu)); names(model_std$std.mu) <- nms_mu
  model_std$std.phi <- rep(NA_real_, length(model_coef$phi)); names(model_std$std.phi) <- nms_phi
  if(has_p0) { model_std$std.p0 <- rep(NA_real_, length(model_coef$p0)); names(model_std$std.p0) <- colnames_X_p0 }
  if(has_p1) { model_std$std.p1 <- rep(NA_real_, length(model_coef$p1)); names(model_std$std.p1) <- colnames_X_p1 }
  
  if (!is.null(fit$sd_report)) {
    sdr_fixed <- summary(fit$sd_report, "fixed")
    
    get_val <- function(pattern, expected, parameter) { 
      idx <- grepl(pattern, rownames(sdr_fixed))
      values <- sdr_fixed[idx, 2] 
      if (length(values) != expected) {
         warning("Could not safely extract ", parameter, ": expected ", expected, " values but found ", length(values), ". NAs introduced.")
         return(rep(NA_real_, expected))
      }
      return(values)
    }
    
    model_std$std.mu  <- get_val("^beta_mu", ncol(X_mu), "mean std errors"); names(model_std$std.mu) <- nms_mu
    model_std$std.phi <- get_val("^beta_phi", ncol(X_phi), "phi std errors"); names(model_std$std.phi) <- nms_phi
    if(has_p0) { model_std$std.p0 <- get_val("^beta_p0", ncol(X_p0), "p0 std errors"); names(model_std$std.p0) <- colnames_X_p0 }
    if(has_p1) { model_std$std.p1 <- get_val("^beta_p1", ncol(X_p1), "p1 std errors"); names(model_std$std.p1) <- colnames_X_p1 }
  }
  
  if (has_random) {
    fit$obj$fn(fit$opt$par)
    
    re_report <- fit$obj$report()
    curr_std_idx <- 1; curr_cor_idx <- 1
    re_variance_list <- list()
    
    for (t_idx in seq_len(re_info$n_re_terms)) {
      n_comp <- re_info$re_term_n_components[t_idx]
      grp_name <- re_info$group_var_names[t_idx]
      cmp_names <- re_info$cnms[[t_idx]]
      
      term_name <- paste0(grp_name, ".", t_idx, ".", paste(cmp_names, collapse = "_"))
      
      p_names <- paste0("Std.Dev.", cmp_names)
      p_est <- re_report$re_std_dev[curr_std_idx:(curr_std_idx + n_comp - 1)]
      
      df_re <- data.frame(Estimate = p_est, `Std. Error` = NA_real_, row.names = p_names, check.names = FALSE)
      
      if (n_comp > 1) {
        n_cor <- n_comp * (n_comp - 1) / 2
        c_mat <- outer(cmp_names, cmp_names, function(r, c) paste0("Corr(", r, ",", c, ")"))
        c_names <- c_mat[lower.tri(c_mat)]
        
        c_est <- re_report$re_cor[curr_cor_idx:(curr_cor_idx + n_cor - 1)]
        df_cor <- data.frame(Estimate = c_est, `Std. Error` = NA_real_, row.names = c_names, check.names = FALSE)
        df_re <- rbind(df_re, df_cor)
        curr_cor_idx <- curr_cor_idx + n_cor
      }
      re_variance_list[[term_name]] <- df_re
      curr_std_idx <- curr_std_idx + n_comp
    }
    
    if (!is.null(fit$sd_report)) {
       sdr_report <- summary(fit$sd_report, "report")
       std_se_full <- sdr_report[grepl("^re_std_dev", rownames(sdr_report)), 2]
       cor_se_full <- if(any(grepl("^re_cor", rownames(sdr_report)))) sdr_report[grepl("^re_cor", rownames(sdr_report)), 2] else numeric(0)
       
       std_ptr <- 1; cor_ptr <- 1
       for (nm in names(re_variance_list)) {
         n_cmp <- sum(grepl("Std.Dev", rownames(re_variance_list[[nm]])))
         re_variance_list[[nm]][1:n_cmp, "Std. Error"] <- std_se_full[std_ptr:(std_ptr + n_cmp - 1)]
         std_ptr <- std_ptr + n_cmp
         
         if (nrow(re_variance_list[[nm]]) > n_cmp) {
           n_cr <- nrow(re_variance_list[[nm]]) - n_cmp
           re_variance_list[[nm]][(n_cmp+1):nrow(re_variance_list[[nm]]), "Std. Error"] <- cor_se_full[cor_ptr:(cor_ptr + n_cr - 1)]
           cor_ptr <- cor_ptr + n_cr
         }
       }
    }
    random_effects_variance <- re_variance_list
  }
  
  logLik_val <- -fit$opt$objective
  npar <- length(fit$opt$par)
  AIC_val <- 2 * npar - 2 * logLik_val
  BIC_val <- log(nrow(clean_data)) * npar - 2 * logLik_val
  
  eta_final <- drop(X_mu %*% model_coef$mu + offset_vec)
  
  if (has_random) {
    par_full <- fit$obj$env$parList(x = fit$opt$par, par = fit$obj$env$last.par)  
    u_vec <- par_full$u_mu
    eta_final <- eta_final + as.vector(Z_mu %*% u_vec)
  }
  
  linkobj <- stats::make.link(family$link_r_name)
  fit_vals <- list(conditional = linkobj$linkinv(eta_final))

  res <- list(obj = fit$obj, 
              opt = fit$opt, 
              sd_report = fit$sd_report, 
              call = cl, 
              formula = formula,
              phi.formula = phi.formula, 
              p0.formula = p0.formula, 
              p1.formula = p1.formula,
              data = data, 
              Y = Y, 
              model = mf, 
              terms = mt, 
              family = family$name, 
              family_object = family, 
              link.mu = linkobj, 
              nobs = nrow(clean_data), 
              has_p0 = has_p0, 
              has_p1 = has_p1,
              has_random_effects_mu = has_random, 
              re_info_mu=re_info, 
              model_coef = model_coef, 
              model_std = model_std, 
              random_effects_variance = random_effects_variance,
              logLik = logLik_val, 
              AIC = AIC_val, 
              BIC = BIC_val, 
              npar = npar, tau = family$tau,
              fitted.values = fit_vals, 
              weights = weights_vec, 
              offset = offset_vec,
              control = control, 
              convergence = fit$convergence, 
              message = fit$message, 
              max_gradient = fit$max_gradient, 
              full_gradient = fit$full_gradient,
              optimizer_warnings = fit$optimizer_warnings, 
              fitting_time = fit$fitting_time)
  
  class(res) <- "unitregTMB"
  return(res)
}
